### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by samcambolt270** [yellows8/hblauncher_loader#13]
according to the error, it appears that it is not detecting the otherapp payload, which i have already placed on the sd card. the file is named properly(as far as i can tell). according to other people, i am supposed to hold y to when starting, and it will connect to the internet and download the correct file, but no matter what, it gives an error. am i doing something wrong?

**Comment by samcambolt270** [comment]
The error goes like this...
hblauncher_loader v1.1 by yellos8.
Getting system-version/system-info etc..
.
_Detected system-version: Old3ds 10.3.0-2
8 USA
Since the X button isn't pressed, this will now check for the otherapp payload o
n SD, with the following filepath:sdmc :
/hblauncherloader_otherapp_payload_old-1
0-3-0-28-usa.bin
Requesting the actual payload url with h
ttp...
Downloading the actual payload with http
...
Failed to download the actual payload wi
th http: 0xd8a0a049.
if the server isn't down, and the http r
equest was actually done, this may mean
your system version or region isn't supp
orted by the hblauncher-payload currentl
y._
I think this error may be because i am using emunand, though i am unsure.

**Comment by voldart** [comment]
I hava a similar problem here. But i think my problem is caused by the new 11.0.0-33 firmware. I just installed am9loaderhax yesterday and when I launch the HBL I encounter with this error :

_hblauncher_loader v1.1 by yellows8.
Getting system-version/system-info etc...
Detected system-version: New3ds 11.0.0-33 USA
Since the X button isn't pressed, this will now check for the otherapp payload on SD, with the following filepath: sdmc :
/hblauncherloader_otherapp_payload_NEW-1
1-0-0-33-USA.bin
Requesting the actual payload URL with HTTP...
Downloading the actual payload with HTTP...
Error: server returned HTTP statuscode 404.
Failed to download the actual payload with HTTP: 0xfffffffe.
If the server isn't down, and the HTTP request was actually done, this may mean your system-version or region isn't supported by the hblauncher-payload currently.
An error occured, please report this to here if it persists (or comment on already existing issue if needed), with an image of your 3DS system: https://github.com/yellows8/hblauncher_loader/issues/
Press the START button to exit._

**Comment by superaxel99** [comment]
I'm having the same exact problem, except I'm on a newer version of the 3DS. I was following this guide, https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax), and in section 6 on, step 15, I get the error. 

> Failed to download the actual payload wi
th http: 0xd8a0a049.

My error is the http: 0xfffffffe

**Comment by yellows8** [comment]
Network fail.

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues/132
