### ISSUE TITLE
Failed to request the actual payload URL:......

### ISSUE THREAD

**Issue by kumwoo** [yellows8/hblauncher_loader#41]
As the instruction https://github.com/Plailect/Guide/wiki/Installing-arm9loaderhax , I've already completed all steps until Section V.8 
But when I launch the Homebrew Launcher, it showed the follewing message in the down screen:

hblauncher_loader v1.2 by yellow8.
Requesting the actual payload URL with HTTPC...
Failed to request the actual payload URL: ...
if the server isn't down, and the HTTP request was actually done, this may mean your system-version or region isn't supported by the *hax payload currently.

My new 3DS is a Japan region one with the firmware 11.2.0-35J

**Comment by puddlesvgc** [comment]
I'm having kind of the same issue on an european O3DS XL on 11.2.0-35E ([image here](http://imgur.com/q5YjmAq)) . Couldn't get any kind of homebrew to work on it and it's really weird. I tried installing basehax, ninjhax, re-installing hblauncher several times (and different versions) and none worked. Actually, when I had v1.1 it actually downloaded the payload, started and then went back to the home menu before the point where red/glitch screen happens. OoOHax magically worked once after 24h hours around it, but it was too late for me and I do not have the game anymore as the copy was not mine and I don't own one.

Details:

1. I had cfw for months now and always worked, build was from cakes time
2. When the 11.0 update striked it was when this started happening, but as I didn't need it I didn't bother
3. I'm gonna downgrade a 11.0.0-33E New3DS XL through DSiWare system transfer and need homebrew to work on my Old
3.1. Following this, I updated the cakes build to Luma3DS (the final part where you need homebrew to install stuff I used OoThax before I had to give it back)
4. Even after Luma installed and I think everything is right hblauncher and ninjhax (the two I have at my disposal since basehax fails to instal everytime) freeze at the same point and send me back to home menu

I think everything that happened to me is written here. Really hoping to be able to fix this, even on the /r/3DShacks and gbatemp irc we couldn't get any fix

**Comment by MeGaPk** [comment]
I have same error too.
HTTP: 0xd8a0a039

hblauncher_loader v1.2
nintendo version: sys 4.5.0-8e

**Comment by MeGaPk** [comment]
Lol, i read not actually guide... sorry.

**Comment by lilkev9412** [comment]
I was doing what puddlesvgc was doing. I also get an error but its different from them. It's 0xd8a0a028

**Comment by scjacobi** [comment]
Having the same problem, error code 0xd8a0a028.  On system 11.2.0-35U, installed hblauncher.cia following this guide: https://3ds.guide/installing-arm9loaderhax  Got to step 13 of "Section VI - Finalizing setup" when I encounter a similar error to puddlesvgc's image with a different error code.  So I can't perform the DSP Dump step.  Not sure if I can proceed or not.  Any suggestions?  Thanks.

**Comment by wizrod** [comment]
"failed to request the actual payload url: 0xd8a0a028" Same thing here, cant dump dsp, not sure what to do. ran the next few steps and they worked fine but homebrew will not run. Server issue?

**Comment by scjacobi** [comment]
Why is this thread closed?  It does not appear that the issue has been fixed, nor has there been any instruction provided on how to resolve the issue?

**Comment by wizrod** [comment]
looks like it was a server issue. It worked perfectly this morning.

**Comment by wizrod** [comment]
My specific issue was fixed. Looks like it was a server side error that was
corrected.
