### ISSUE TITLE
server returned http statuscode 404

### ISSUE THREAD

**Issue by criminallysane** [yellows8/hblauncher_loader#51]
Following instructions very carefully, no help on this I can find

**Comment by ralphwicked** [comment]
what instructions?

**Comment by vincentquy** [comment]
I have the same problem as criminallysane's. I read in his other post that his 3DS version is now 11.3.0 which is currently not supported yet. The reason is in Plailect Guide, this step tell us to update system: 
"7. Update your 3DS by going to System Settings, then “Other Settings”, then going all the way to the right and using “System Update”
Updates while using A9LH + Luma (what you have) are safe, stop asking about it."
So I want to ask if there is anyway I can downgrade my console back to 11.2 ?

**Comment by dillpill321** [comment]
Yep, same thing happened to me just now.

**Comment by damittt** [comment]
Well damn just as I thought I was making progress, same thing happened to me. I thought I had messed this up some how

**Comment by CoryZ40** [comment]
Mine used to work, no longer does. Getting 404.

**Comment by jorgen3** [comment]
I just got this too. I am on 11.3 does that have anything to do with it

**Comment by netozeppelin** [comment]
Me too... 404.

**Comment by Boneix1992** [comment]
Me too..

**Comment by LACHSPEED** [comment]
Same situation, followed the instructions on 3ds.guide, updating to 11.3.0. Homebrew Launcher returns 404 and Soundhax results in a system error.

**Comment by yukikiru** [comment]
After updating to 11.3.0 homebrew launcher is no longer useable, Have to wait for a version that's compatible with 11.3.0. Also, soundhax only worked up to 11.2.0.

**Comment by yellows8** [comment]
That error specifically says {system-version not supported} ........
